codecov:
  require_ci_to_pass: false
github_checks:
  annotations: false
coverage:
  status:
    project:
      default: false
      cmd:
        paths:
          - "cmd/"
        target: 75%
        informational: true
      internal:
        paths:
          - "internal/"
        target: 75%
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "**/*_mocks.go"
