# Build the manager binary
FROM golang:1.22 as builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace

# Copy the go source
COPY go.mod go.mod
COPY go.sum go.sum
COPY main.go main.go
COPY cmd/agent/ cmd/agent/
COPY api/ api/
COPY internal/ internal/
COPY pkg/ pkg/
COPY vendor/ vendor/

ARG TAG=v0.0.0
ARG COMMIT=""
ARG COMMITDATE=""

# Build agent binary
RUN CGO_ENABLED=1 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build \
    -ldflags "-w -s  \
    -X github.com/rancher-sandbox/cluster-api-provider-elemental/internal/version.Version=$TAG  \
    -X github.com/rancher-sandbox/cluster-api-provider-elemental/internal/version.Commit=$COMMIT  \
    -X github.com/rancher-sandbox/cluster-api-provider-elemental/internal/version.CommitDate=$COMMITDATE"  \
    -a -o elemental-agent main.go

# Build elemental-toolkit plugin
RUN CGO_ENABLED=1 go build \
    -buildmode=plugin \
    -o elemental.so internal/agent/plugin/elemental/elemental.go

# Build dummy plugin
RUN CGO_ENABLED=1 go build \
    -buildmode=plugin \
    -o dummy.so internal/agent/plugin/dummy/dummy.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/elemental-agent /elemental-agent
COPY --from=builder /workspace/elemental.so /elemental.so
COPY --from=builder /workspace/dummy.so /dummy.so
USER 65532:65532

ENTRYPOINT ["/"]
