resources:
- manager.yaml
- configmap.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/rancher-sandbox/cluster-api-provider-elemental
  newTag: IMAGE_TAG
