apiVersion: v1
kind: Service
metadata:
  name: controller-manager
  namespace: system
spec:
  selector:
    app.kubernetes.io/name: elemental-controller-manager
  ports:
    - protocol: TCP
      port: 9090
      targetPort: api
