apiVersion: v1
kind: Service
metadata:
  name: controller-manager
  namespace: system
spec:
  selector:
    control-plane: controller-manager
  ports:
    - protocol: TCP
      port: 9090
      targetPort: api
