apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cni: ${CLUSTER_NAME}-crs-0
    crs: "true"
  name: ${CLUSTER_NAME}
  namespace: ${NAMESPACE}
spec:
  clusterNetwork:
    services:
      cidrBlocks: ${SERVICE_CIDR:=["10.96.0.0/12"]}
    pods:
      cidrBlocks: ${POD_CIDR:=["10.244.0.0/16"]}
    serviceDomain: ${SERVICE_DOMAIN:="cluster.local"}
  topology:
    class: kubeadm-v0.5.0
    version: ${KUBERNETES_VERSION:="1.28.4"}
    controlPlane:
      metadata: {}
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    workers:
      machineDeployments:
      - class: kubeadm-v0.5.0-default-worker
        name: md-0
        replicas: ${WORKER_MACHINE_COUNT}
    variables:
    - name: controlPlaneEndpointHost
      value: "${CONTROL_PLANE_ENDPOINT_HOST:=""}"
    - name: controlPlaneEndpointPort
      value: ${CONTROL_PLANE_ENDPOINT_PORT:=6443}
    - name: vipInterface
      value: "${VIP_INTERFACE:="eth0"}"
