apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: k3s-single-node-v0.5.0
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KThreesControlPlane
      name: k3s-single-node-v0.5.0-control-plane
    machineInfrastructure:
      ref:
        kind: ElementalMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: k3s-single-node-v0.5.0-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: ElementalClusterTemplate
      name: k3s-single-node-v0.5.0-cluster
  variables:
    - name: controlPlaneEndpointHost
      required: true
      schema:
        openAPIV3Schema:
          type: string
    - name: controlPlaneEndpointPort
      required: true
      schema:
        openAPIV3Schema:
          type: integer
          default: 6443
    - name: k3sVersion
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: "v1.28.4+k3s2"
  patches:
    - name: elementalClusterTemplate
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: ElementalClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: add
              path: "/spec/template/spec/controlPlaneEndpoint/host"
              valueFrom:
                variable: controlPlaneEndpointHost
            - op: add
              path: "/spec/template/spec/controlPlaneEndpoint/port"
              valueFrom:
                variable: controlPlaneEndpointPort
    - name: kThreesControlPlane
      definitions:
        - selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: KThreesControlPlane
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: add
              path: "/spec/version"
              valueFrom:
                variable: k3sVersion
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElementalClusterTemplate
metadata:
  name: k3s-single-node-v0.5.0-cluster
spec:
  template:
    spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KThreesControlPlane
metadata:
  name: k3s-single-node-v0.5.0-control-plane
spec:
  kthreesConfigSpec:
    serverConfig:
      disableExternalCloudProvider: true
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElementalMachineTemplate
metadata:
  name: k3s-single-node-v0.5.0-control-plane
spec:
  template:
    spec: {}
