apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: kubeadm
spec:
  controlPlane:
    metadata:
      annotations:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: kubeadm-control-plane
    machineInfrastructure:
      ref:
        kind: ElementalMachineTemplate
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        name: kubeadm-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: ElementalClusterTemplate
      name: kubeadm-cluster
  workers:
    machineDeployments:
      - class: kubeadm-default-worker
        template:
          bootstrap:
            ref:
              apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
              kind: KubeadmConfigTemplate
              name: kubeadm-default-worker-bootstrap-template
          infrastructure:
            ref:
              apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
              kind: ElementalMachineTemplate
              name: kubeadm-default-worker-machine-template
  variables:
    - name: controlPlaneEndpointHost
      required: true
      schema:
        openAPIV3Schema:
          type: string
    - name: controlPlaneEndpointPort
      required: true
      schema:
        openAPIV3Schema:
          type: integer
          default: 6443
    - name: vipInterface
      required: true
      schema:
        openAPIV3Schema:
          type: string
          default: "eth0"
  patches:
    - name: elementalClusterTemplate
      definitions:
        - selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: ElementalClusterTemplate
            matchResources:
              infrastructureCluster: true
          jsonPatches:
            - op: add
              path: "/spec/template/spec/controlPlaneEndpoint/host"
              valueFrom:
                variable: controlPlaneEndpointHost
            - op: add
              path: "/spec/template/spec/controlPlaneEndpoint/port"
              valueFrom:
                variable: controlPlaneEndpointPort
    - name: kubeadmControlPlaneTemplate
      definitions:
        - selector:
            apiVersion: controlplane.cluster.x-k8s.io/v1beta1
            kind: KubeadmControlPlaneTemplate
            matchResources:
              controlPlane: true
          jsonPatches:
            - op: add
              path: "/spec/template/spec/kubeadmConfigSpec/files"
              valueFrom:
                template: |
                  - content: |
                      apiVersion: v1
                      kind: Pod
                      metadata:
                        creationTimestamp: null
                        name: kube-vip
                        namespace: kube-system
                      spec:
                        containers:
                        - args:
                          - manager
                          env:
                          - name: vip_arp
                            value: "true"
                          - name: port
                            value: {{ .controlPlaneEndpointPort }}
                          - name: vip_interface
                            value: {{ .vipInterface }}
                          - name: vip_cidr
                            value: "32"
                          - name: cp_enable
                            value: "true"
                          - name: cp_namespace
                            value: kube-system
                          - name: vip_ddns
                            value: "false"
                          - name: svc_enable
                            value: "true"
                          - name: vip_leaderelection
                            value: "true"
                          - name: vip_leaseduration
                            value: "5"
                          - name: vip_renewdeadline
                            value: "3"
                          - name: vip_retryperiod
                            value: "1"
                          - name: address
                            value: {{ .controlPlaneEndpointHost }}
                          image: ghcr.io/kube-vip/kube-vip:v0.6.4
                          imagePullPolicy: Always
                          name: kube-vip
                          resources: {}
                          securityContext:
                            capabilities:
                              add:
                              - NET_ADMIN
                              - NET_RAW
                              - SYS_TIME
                          volumeMounts:
                          - mountPath: /etc/kubernetes/admin.conf
                            name: kubeconfig
                        hostAliases:
                        - hostnames:
                          - kubernetes
                          ip: 127.0.0.1
                        hostNetwork: true
                        volumes:
                        - hostPath:
                            path: /etc/kubernetes/admin.conf
                          name: kubeconfig
                      status: {}
                    owner: root:root
                    path: /etc/kubernetes/manifests/kube-vip.yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElementalClusterTemplate
metadata:
  name: kubeadm-cluster
spec:
  template:
    spec:
      controlPlaneEndpoint: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlaneTemplate
metadata:
  name: kubeadm-control-plane
spec:
  template:
    spec:
      kubeadmConfigSpec:
        clusterConfiguration:
          apiServer:
            certSANs:
            - localhost
            - 127.0.0.1
            - 0.0.0.0
          controllerManager:
            extraArgs:
              enable-hostpath-provisioner: "true"
        initConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
        joinConfiguration:
          nodeRegistration:
            kubeletExtraArgs:
              eviction-hard: nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElementalMachineTemplate
metadata:
  name: kubeadm-control-plane
spec:
  template:
    spec: {}
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: kubeadm-default-worker-bootstrap-template
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: ElementalMachineTemplate
metadata:
  name: kubeadm-default-worker-machine-template
spec:
  template:
    spec: {}
