name: "Elemental Rootfs Layout Settings"
stages:
  initramfs:
    - if: '[ ! -f /run/cos/recovery_mode ]'
      commands:
      - |
        if [ ! -e /usr/local/etc/hostname ]; then
          mkdir -p /usr/local/etc 
          echo rancher-${RANDOM} > /usr/local/etc/hostname
        fi
        ln -sf /usr/local/etc/hostname /etc/hostname
    - if: '[ ! -f "/run/cos/recovery_mode" ]'
      name: "Persist /etc/machine-id"
      commands:
      - |
        # persist machine-id
        if [ -s /usr/local/etc/machine-id ]; then
          cat /usr/local/etc/machine-id > /etc/machine-id
        else
          mkdir -p /usr/local/etc
          cp /etc/machine-id /usr/local/etc
        fi
    - name: "Create essential persistent paths"
      directories:
      - path: /usr/local/bin
  rootfs:
    - if: '[ ! -f "/run/cos/recovery_mode" ]'
      name: "Layout configuration"
      environment_file: /run/cos/cos-layout.env
      environment:
        OVERLAY: "tmpfs:25%"
        RW_PATHS: "/var /etc /srv"
        PERSISTENT_STATE_PATHS: >-
          /etc/systemd
          /etc/rancher
          /etc/ssh
          /etc/iscsi 
          /etc/cni
          /home
          /opt
          /root
          /usr/libexec
          /var/log
          /var/lib/elemental
          /var/lib/rancher
          /var/lib/kubelet
          /var/lib/NetworkManager
          /var/lib/longhorn
          /var/lib/cni
          /var/lib/calico
        PERSISTENT_STATE_BIND: "true"
    - if: '[ -f "/run/cos/recovery_mode" ]'
      # omit the persistent partition on recovery mode
      name: "Layout configuration for recovery"
      environment_file: /run/cos/cos-layout.env
      environment:
        OVERLAY: "tmpfs:25%"
