# TODO: kubeadm binaries needs to be in PATH for the bootstrap to work. 
#       They should live in /usr/local/sbin, but that requires a newer version of elemental-toolkit.
#       This is just a dirty workaround.
name: "Kubeadm /usr/local/sbin hack"
stages:
  boot:
    - if: '[ -d "/opt/kubeadm/bin" ]'
      name: "Link kubeadm binaries to /usr/local/sbin"
      commands: 
        - "ln -s /opt/kubeadm/bin/kubeadm /usr/local/sbin/kubeadm"
        - "ln -s /opt/kubeadm/bin/kubelet /usr/local/sbin/kubelet"
        - "ln -s /opt/kubeadm/bin/kubectl /usr/local/sbin/kubectl"
        - "ln -s /opt/kubeadm/bin/crictl /usr/local/sbin/crictl"
