# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default

# Set common labels: https://cluster-api.sigs.k8s.io/developer/providers/contracts.html#api-version-labels
commonlabels:
  cluster.x-k8s.io/v1beta1: v1beta1

resources:
- bases/infrastructure.cluster.x-k8s.io_elementalhosts.yaml
- bases/infrastructure.cluster.x-k8s.io_elementalmachines.yaml
- bases/infrastructure.cluster.x-k8s.io_elementalmachinetemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_elementalclusters.yaml
- bases/infrastructure.cluster.x-k8s.io_elementalclustertemplates.yaml
- bases/infrastructure.cluster.x-k8s.io_elementalregistrations.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_elementalhosts.yaml
#- path: patches/webhook_in_elementalmachines.yaml
#- path: patches/webhook_in_elementalmachinetemplates.yaml
#- path: patches/webhook_in_elementalclusters.yaml
#- path: patches/webhook_in_elementalclustertemplates.yaml
#- path: patches/webhook_in_elementalregistrations.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_elementalhosts.yaml
#- path: patches/cainjection_in_elementalmachines.yaml
#- path: patches/cainjection_in_elementalmachinetemplates.yaml
#- path: patches/cainjection_in_elementalclusters.yaml
#- path: patches/cainjection_in_elementalclustertemplates.yaml
#- path: patches/cainjection_in_elementalregistrations.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
