name: Unit tests
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: tests-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
    - name: Run tests
      run: make tests
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.out
